# Sonja Projects | Author: Sonja Sahebzad
# Run from final_project. This regression check never rewrites model metrics.
library(shiny)
library(data.table)
args <- commandArgs(trailingOnly=TRUE)
reference <- if(length(args)) normalizePath(args[1],winslash="/") else
  stop("Supply the preserved v1 predictor.R path for equivalence checking.")
project <- if(length(args)>1L) normalizePath(args[2],winslash="/") else normalizePath("..",winslash="/")
old <- new.env()
sys.source(reference,envir=old)
source("app/predictor.R")
model <- prepare_predictor(readRDS("app/model.rds"))
cases <- rbindlist(lapply(c("data/adaptation/development.csv","data/final_product/final_test.csv"),
  function(f) fread(file.path(project,f))[,.(prefix)]))
stopifnot(nrow(cases)==1500L)
for (phrase in cases$prefix) {
  before <- old$predict_word(model,phrase)
  after <- predict_word(model,phrase)
  stopifnot(identical(before$words,after$words),identical(before$scores,after$scores),
    after$context_words==min(after$input_words,after$order-1L))
}
p <- predict_word(model,"top of the")
stopifnot(p$context_words==3L,p$input_words==3L,p$order==5L,p$start_markers==1L)
p <- predict_word(model,"We reached the top of the")
stopifnot(p$input_words==6L,p$context_words==4L,p$context=="the top of the")
app_env <- new.env()
local({
  previous <- setwd("app"); on.exit(setwd(previous))
  sys.source("app.R",envir=app_env)
})
testServer(app_env$server, {
  session$setInputs(phrase="",automatic=TRUE)
  session$flushReact()
  session$setInputs(phrase="top of the ")
  stopifnot(is.null(result()))
  session$elapse(100)
  stopifnot(is.null(result()))
  session$elapse(60)
  stopifnot(result()$context_words==3L,identical(last_phrase(),"top of the "))
  session$setInputs(phrase="top of the morn")
  session$elapse(160)
  stopifnot(is.null(result())) # incomplete word is never treated as completed automatically
  session$setInputs(phrase="top of the morning ")
  session$elapse(160)
  stopifnot(!is.null(result()),identical(last_phrase(),"top of the morning "))
  session$setInputs(phrase="We reached the top of the",predict=1L)
  stopifnot(result()$input_words==6L,result()$context_words==4L)
  session$elapse(160)
  stopifnot(identical(last_phrase(),"We reached the top of the"))
  session$setInputs(phrase="Another sentence. And then ")
  session$setInputs(phrase="Another sentence. And then more ")
  session$elapse(160)
  stopifnot(identical(last_phrase(),"Another sentence. And then more "))
  session$setInputs(phrase="Hello\nworld, ")
  session$elapse(160)
  stopifnot(result()$normalized=="hello world")
  session$setInputs(phrase="Please finish this ")
  session$setInputs(phrase="")
  session$elapse(160)
  stopifnot(is.null(result()),is.null(error()))
  session$setInputs(automatic=FALSE,phrase="A new phrase ")
  session$elapse(160)
  stopifnot(is.null(result()))
  session$setInputs(predict=2L)
  stopifnot(!is.null(result()))
  session$setInputs(phrase="",predict=3L)
  stopifnot(is.null(result()),!is.null(error()))
  session$setInputs(phrase=paste(rep("word",110),collapse=" "),predict=4L)
  stopifnot(is.null(result()),grepl("500",error()))
  session$setInputs(automatic=TRUE,phrase="xqzz qzzx ")
  session$elapse(160)
  stopifnot(length(result()$words)==3L,is.null(error()))
})
cat("PASS: identical words and scores on 1,500 existing cases; no accuracy retuning.\n")
cat("PASS: three typed words distinguished from start marker; six-word input reports four-word context.\n")
cat("PASS: automatic word-boundary refresh, continuing text, partial-word pause, punctuation/newlines,\n")
cat("      rapid replacement, clearing with pending timer, manual mode, length limit and fallback.\n")
cat("PASS: 150 ms automatic debounce, absent at 100 ms and present after 160 ms in virtual-time tests.\n")
cat("Model MD5:",unname(tools::md5sum("app/model.rds")),"\n")
